import type { Metadata } from "next";
import { Geist, Geist_Mono, Istok_Web, Inter } from "next/font/google";
import "./globals.css";

const istokWeb = Istok_Web({
  variable: "--font-istok-web",
  weight: ["400", "700"]
});

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "300", "400", "700", "900"]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${istokWeb.variable} ${inter.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
